version: "2.1"

services:
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cosmind
      POSTGRES_USER: cosmind
      POSTGRES_PASSWORD: eefi4thee6phiQu9Owushi4deihii5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./.data:/var/lib/postgresql/data"
  cosmind:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cosmind
