ALTER TABLE idea
ADD COLUMN created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE project
ADD COLUMN created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE story
ADD COLUMN created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();